#!/usr/bin/env python3

import skilstak.colors as c
import time as t

"""Hello-3 Types Of Hello Program """

def multi():
    """Hello World Las Vegas Style Baby"""
    while True:
        print(c.clear + c.multi("Hello World"))
        t.sleep(.1)

def color():
    """fills screen with buttyful hellow worlds""" 
    print(c.rc() + "Hello World" + c.reset, end=" ")

def hello():
    """a random hello world"""
    print(c.clear + c.rc + c.reset +"Hello World") 
if __name__ == '__main__':
    try:
        #hello()
        #color()
        multi()
    except KeyboardInterrupt:
        print(c.clear + c.base00 + '''
               _________
            __|__|_____| ''' + c.green + '''
          /  Holy  \ 
         /   Hand   \ 
        /  Granada   \ 
       |     of      |
       |   the holy  |
        \    Grail  /
         \_________/       
                
                ''')
        exit()
